# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 977777f4e8483b5db5cd34ac748410e1f3b94f8bf9486808ac3eb4032648ec34cb6f2bb7c2e5e1310236f0eb2f4410206a20e0be5f47a9e15d5968ff32ce4aab

test:
  secret_key_base: 343857d4bfa889a144b5c95a49a8d18dda4b4f0834c2ce6555b97d943c7b6431d874f892c58344437eb9eaae6af93169adca934d2b25001c495d1678cc9946c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
