# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8080b6001fb2a829dd42d64a51e8a64e3117c69c235a703545378458f0876a963144d6c71bfa9ce3ad3c8ad9ff1b1befdc55e4f904a336bb1be34271d1a8b17c

test:
  secret_key_base: 909f3f941bc8d32f9bd71735ec787d6118b642be96712be099cb8bea2b6e200dc1935c63c717fc154a9a712669cf0aa9358bf689e4fd3989d20d40247102d85f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
